/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "chess.start", input: never, result: Chess } | 
        { key: "echo", input: string, result: string },
    mutations: never,
    subscriptions: never
};

export type Chess = { board: ChessBoard; team_to_move: Team; halfmove_clock: number; fullmove_clock: number }

export type Team = "Black" | "White"

export type ChessBoard = ChessPiece | null[]

export type ChessPieceVariant = "Pawn" | "Bishop" | "Knight" | "Rook" | "Queen" | "King"

export type ChessPiece = { team: Team; variant: ChessPieceVariant }
